Repository wecode-bootcamp-korea/20-1st-YOUNGCHAPEDIA-frontend, pull requests merged in 2021-05, with the labels that each got.

#5 [20기 임유진] Add : Navbar 레이아웃 1차 완성
  src/Routes.js
  src/pages/CommonComponents/Navbar.js
  src/pages/CommonComponents/Navbar.scss
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#2 [20기 이다슬] Modify: 3차 리뷰 수정완료
  package-lock.json
  public/data/MainMockData.json
  src/pages/CommonComponents/Navbar.scss
  src/pages/Main/Components/MainSection/MainSection.js
  src/pages/Main/Components/MainSection/MainSection.scss
  src/pages/Main/Components/MainSectionMovieList/MainSectionMovieList.js
  src/pages/Main/Components/MainSectionMovieList/MainSectionMovieList.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/MovieDetail/MovieDetail.js
Labels: Status: Accepted

#7 [20기 임유진] Fix : NavBar z-index 빠져서 추가했습니다 merge 부탁드립니다!
  src/pages/CommonComponents/Navbar.scss
Labels: Status: Accepted

#3 [20기 전용민] Add: 영화 상세 페이지 레이아웃 conflict 해결, merge 부탁드립니다!
  src/Routes.js
  src/pages/MovieDetail/Components/LeaveCommentSection/LeaveCommentSection.js
  src/pages/MovieDetail/Components/LeaveCommentSection/LeaveCommentSection.scss
  src/pages/MovieDetail/Components/MovieBannerSection/MovieBannerSection.js
  src/pages/MovieDetail/Components/MovieBannerSection/MovieBannerSection.scss
  src/pages/MovieDetail/Components/MovieDetailContentsSection/MovieDetailContentsSection.js
  src/pages/MovieDetail/Components/MovieDetailContentsSection/MovieDetailContentsSection.scss
  src/pages/MovieDetail/MovieDetail.js
  src/pages/MovieDetail/MovieDetail.scss
Labels: Status: 리뷰 요청

#9 [20기 임유진] Add : Modal 컴포넌트 1차 리뷰 반영
  src/pages/CommonComponents/Modal.js
  src/pages/CommonComponents/Modal.scss
  src/pages/CommonComponents/Navbar.js
  src/pages/CommonComponents/Navbar.scss
  src/pages/CommonComponents/test.js
Labels: Status: Accepted

#10 [20기 임유진] Modify : Footer 높이 조금 늘리기
  src/pages/CommonComponents/Footer.scss
Labels: Status: Accepted

#12 [20기 임유진] Add : config.js API URL 추가
  src/config.js
Labels: Status: Accepted

#8 [20기 임유진] Fix : 평가하기 페이지 컨플릭트 해결
  public/data/expectedData.json
  public/data/movieMockData.json
  src/Routes.js
  src/pages/ReviewPage/ReviewPage.js
  src/pages/ReviewPage/ReviewPage.scss
  src/pages/ReviewPage/component/ReviewMovieList.js
  src/pages/ReviewPage/component/ReviewMovieList.scss
  src/utils/throttle.js
Labels: Status: Accepted

#17 [20기 임유진] Fix : 컨플릭트 해결 (모달창 사이트 로고 부분 레이아웃 컴포넌트)
  src/Routes.js
  src/pages/CommonComponents/ModalLogoLayout.js
  src/pages/CommonComponents/ModalLogoLayout.scss
Labels: Status: Accepted

#15 [20기 임유진] Add : Nav바 로그인시 해당 state true로 전환하는 함수 추가
  src/pages/CommonComponents/Navbar.js
Labels: Status: 리뷰 요청

#16 [20기 임유진] Add & Fix : 로그인/회원가입 폼 conflict 해결, 로그인 성공시 Nav 로그인 여부 state 변경 연결, onBlur 이벤트 추가
  src/config.js
  src/pages/Login-SignIn/Login.js
  src/pages/LoginSignIn/LoginSignInForm.js
  src/pages/LoginSignIn/LoginSignInForm.scss
Labels: Status: Accepted

#18 [20기 전용민] Add: 영화 상세 페이지 비슷한 영화 섹션 레이아웃, 스크롤 이벤트 구현
  public/data/SimilarMovieMockData.json
  src/Routes.js
  src/pages/MovieDetail/Components/MovieDetailContentsSection/Components/SimilarMovie/SimilarMovie.js
  src/pages/MovieDetail/Components/MovieDetailContentsSection/Components/SimilarMovie/SimilarMovie.scss
  src/pages/MovieDetail/Components/MovieDetailContentsSection/MovieDetailContentsSection.js
  src/pages/MovieDetail/Components/MovieDetailContentsSection/MovieDetailContentsSection.scss
Labels: Status: 수정 요청

#14 [20기 전용민] Add: 영화 상세 페이지 코멘트 슬라이드 부분 구현 1차 리뷰 반영
  public/data/MovieDetailPageComments.json
  src/pages/MovieDetail/Components/MovieDetailContentsSection/Components/Comment/Comment.js
  src/pages/MovieDetail/Components/MovieDetailContentsSection/Components/Comment/Comment.scss
  src/pages/MovieDetail/Components/MovieDetailContentsSection/MovieDetailContentsSection.js
  src/pages/MovieDetail/Components/MovieDetailContentsSection/MovieDetailContentsSection.scss
Labels: Status: 리뷰 요청

#20 [20기 임유진] Modify : 마이페이지 백엔드 테스트 완료, 데이터 구조 변경에 맞게 수정
  public/data/userArchiveData.json
  public/data/userWantedData.json
  src/Routes.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPage.scss
Labels: Status: Accepted

#24 [20기 임유진] Modify : config.js 합의된 API 최종버전
  src/config.js
Labels: Status: Accepted

#25 [20기 임유진] Modify : 공용 scss 수정
  public/favicon-16x16.png
  src/pages/CommonComponents/test.js
  src/styles/_variables.scss
  src/styles/common.scss
Labels: Status: Accepted

#22 [20기 임유진] Fix : 취향분석 페이지 컨플릭트 해결
  public/data/analyzeGenresMockData.json
  public/data/analyzeStarRatesMockData.json
  src/Routes.js
  src/pages/AnalyzeTest/AnalyzeTest.js
  src/pages/AnalyzeTest/AnalyzeTest.scss
  src/pages/AnalyzeTest/Component/AnalyzeCardLayout.js
  src/pages/AnalyzeTest/Component/AnalyzeCardLayout.scss
  src/pages/AnalyzeTest/Component/AnalyzeFavorite.js
  src/pages/AnalyzeTest/Component/AnalyzeFavorite.scss
  src/pages/AnalyzeTest/Component/AnalyzeStarRate.js
  src/pages/AnalyzeTest/Component/AnalyzeStarRate.scss
  src/pages/CommonComponents/Navbar.js
Labels: Status: Accepted

#27 [20기 임유진] Modify & Fix : NavBar isUserLogined 초기값 수정, 컨플릭트 해결
  src/pages/CommonComponents/Navbar.js
  src/pages/CommonComponents/Navbar.scss
Labels: Status: Accepted

#11 [20기 이다슬] Modify : 메인페이지 슬라이더 기능 3차 리뷰 반영
  public/data/MainMockData.json
  public/data/boxoffice.json
  public/data/movieMockData.json
  public/data/netflix.json
  public/data/watcha.json
  src/Routes.js
  src/config.js
  src/pages/Main/Components/MainSection/MainSection.js
  src/pages/Main/Components/MainSection/MainSection.scss
  src/pages/Main/Components/MainSectionMovieList/MainSectionMovieList.js
  src/pages/Main/Components/MainSectionMovieList/MainSectionMovieList.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: 리뷰 요청

#32 [20기 임유진] Add : 별점 컴포넌트 POST, GET 요청 함수 분리
  src/pages/CommonComponents/StarRating.js
  src/pages/ReviewPage/Component/ReviewMovieList.js
Labels: Status: Accepted

#23 [20기 이다슬] Modify : 1차 리뷰 반영
  boxoffice.json
  public/data/MainMockData.json
  public/data/analyzeGenresMockData.json
  public/data/analyzeStarRatesMockData.json
  public/data/boxoffice4.json
  public/data/expectedData.json
  public/data/movieMockData.json
  public/data/userArchiveData.json
  public/data/userWantedData.json
  src/pages/Main/Components/MainSection/MainSection.js
  src/pages/Main/Components/MainSectionMovieList/MainSectionMovieList.js
  src/pages/Main/Components/MainSectionMovieList/MainSectionMovieList.scss
  src/pages/Main/Main.js
Labels: Status: Accepted

#31 [20기 이다슬] 메인/상세페이지 동적라우팅 Setting
  src/Routes.js
  src/pages/Main/Components/MainSection/MainSection.js
  src/pages/Main/Components/MainSectionMovieList/MainSectionMovieList.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: Accepted

#33 [20기 전용민] ADD : 상세페이지 별점 post,get
  src/pages/CommonComponents/StarRating.js
  src/pages/MovieDetail/Components/MovieBannerSection/MovieBannerSection.js
  src/pages/MovieDetail/Components/MovieBannerSection/MovieBannerSection.scss
  src/pages/MovieDetail/Components/MovieDetailContentsSection/MovieDetailContentsSection.js
  src/pages/MovieDetail/MovieDetail.js
Labels: Status: Accepted

#34 [20기 임유진] Modify : 반복되는 const 수정
  src/pages/MovieDetail/MovieDetail.js
Labels: Status: Accepted

#38 [20기 임유진] Modify : scss 수정, 상세페이지 별점/보고싶어요 로직 수정, 회원가입 alert 수정
  .vscode/extensions.json
  src/config.js
  src/pages/CommonComponents/ModalLogoLayout.scss
  src/pages/CommonComponents/Navbar.scss
  src/pages/CommonComponents/StarRating.js
  src/pages/LoginSignIn/LoginSignInForm.js
  src/pages/Main/Components/MainSection/MainSection.js
  src/pages/Main/Components/MainSectionMovieList/MainSectionMovieList.js
  src/pages/Main/Components/MainSectionMovieList/MainSectionMovieList.scss
  src/pages/MovieDetail/Components/LeaveCommentSection/CommentModal.scss
  src/pages/MovieDetail/Components/LeaveCommentSection/LeaveCommentSection.scss
  src/pages/MovieDetail/Components/MovieBannerSection/MovieBannerSection.js
  src/pages/MovieDetail/Components/MovieBannerSection/MovieBannerSection.scss
  src/pages/MovieDetail/Components/MovieDetailContentsSection/MovieDetailContentsSection.js
  src/pages/MovieDetail/MovieDetail.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPage.scss
  src/pages/ReviewPage/ReviewPage.js
  src/styles/common.scss
Labels: Status: 리뷰 요청
